import { z } from 'zod';

const severitySubmissionSchema = z.object({
  contextId: z.uuid('Invalid contextId format'),
  level: z.number().int().min(1).max(5),
  label: z.string().min(1).max(120).optional(),
});

export const chatSchema = z.object({
  body: z.object({
    query: z.string().min(1, 'Query is required'),
    /** Ephemeral session ID generated by the frontend per chat session (per app run). */
    clientChatSessionId: z.uuid('clientChatSessionId must be a valid UUID'),
    resolvedPetId: z.uuid().optional(),
    contextId: z.uuid().optional(),
    severitySubmission: severitySubmissionSchema.optional(),
  }).superRefine((body, ctx) => {
    if (
      body.severitySubmission &&
      body.contextId &&
      body.severitySubmission.contextId !== body.contextId
    ) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          'severitySubmission.contextId must match contextId when both are provided',
        path: ['severitySubmission', 'contextId'],
      });
    }
  }),
});

export type ChatRequest = z.infer<typeof chatSchema>;
export type SeveritySubmissionInput = z.infer<typeof severitySubmissionSchema>;
