-- AlterTable
ALTER TABLE "pets" ALTER COLUMN "birth_date" DROP NOT NULL,
ALTER COLUMN "weight" DROP NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "reminders" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
